// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_pinglei_to_clothes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_pinglei_to_clothes));
        
        string IMigrationMetadata.Id
        {
            get { return "201305221518194_add_pinglei_to_clothes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
