// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class create_user_clothes_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_user_clothes_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "201307121446254_create_user_clothes_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
