// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_something : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_something));
        
        string IMigrationMetadata.Id
        {
            get { return "201305241124181_add_something"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
