// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_clothes_IsDelete_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_clothes_IsDelete_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201305240139328_add_clothes_IsDelete_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
