// <auto-generated />
namespace EPManageWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_Order_into_Tag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Order_into_Tag));
        
        string IMigrationMetadata.Id
        {
            get { return "201308280313110_add_Order_into_Tag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
