package org.apache.jsp.authority;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class grant_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
String webContext = request.getContextPath(); 
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>成衣维修</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/themes/default/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(webContext);
      out.write("/css/cmcommon.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/demo/demo.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/themes/icon.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/src/jquery.parser.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar selectUserID;\r\n");
      out.write("\t\r\n");
      out.write("\t\t $(function() {  \r\n");
      out.write("         \t$(document).ready(function() {  \r\n");
      out.write("          \t\tinitTree();\r\n");
      out.write("          \t\t\r\n");
      out.write("        \t});  \r\n");
      out.write("  \r\n");
      out.write("   \t\t\t$('#roleGrid').datagrid({\r\n");
      out.write("\t\t\ttitle : '角色',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\twidth:400,\r\n");
      out.write("\t\t\theight : 350,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tautoRowHeight : false,\r\n");
      out.write("\t\t\tstriped : true,\r\n");
      out.write("\t\t\tcollapsible : true,\r\n");
      out.write("\t\t\turl :  $('#webContext').attr('value')+'/rest/DrpUser/queryrole/-1',\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\tremoteSort : false,\r\n");
      out.write("\t\t\t//idField:'rolename,roledesc',\r\n");
      out.write("\t\t\tcolumns : [ [\r\n");
      out.write("\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfield : 'roleid',\r\n");
      out.write("\t\t\t\ttitle : '主键',\r\n");
      out.write("\t\t\t\thidden : true\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'rolename',\r\n");
      out.write("\t\t\t\ttitle : '角色名称',\r\n");
      out.write("\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'roledesc',\r\n");
      out.write("\t\t\t\ttitle : '角色描述',\r\n");
      out.write("\t\t\t\twidth :200,\r\n");
      out.write("\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t] ],\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\r\n");
      out.write("\t\t\ttoolbar : [ {\r\n");
      out.write("\t\t\t\tid : 'btnadd',\r\n");
      out.write("\t\t\t\ttext : '新增',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t$('#roleGridNo').datagrid('options').url = $('#webContext').attr('value')+'/rest/DrpUser/queryRoleNoGrant/'+selectUserID;\r\n");
      out.write("\t\t\t\t\t$('#roleGridNo').datagrid('load');\r\n");
      out.write("\t\t\t\t\topenRoleHidden();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tid : 'btncut',\r\n");
      out.write("\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-cut',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t$('#btnsave').linkbutton('enable');\r\n");
      out.write("\t\t\t\t\tvar row = $('#roleGrid').datagrid('getSelected');\r\n");
      out.write("\t\t\t\t\tif (row) { \r\n");
      out.write("\t\t\t\t\t\tvar rowIndex = $('#roleGrid').datagrid('getRowIndex', row);\r\n");
      out.write("\t\t\t\t\t\t$('#roleGrid').datagrid('deleteRow', rowIndex);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\tid : 'btnsave',\r\n");
      out.write("\t\t\t\ttext : '保存',\r\n");
      out.write("\t\t\t\tdisabled : true,\r\n");
      out.write("\t\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t$('#btnsave').linkbutton('disable');\r\n");
      out.write("\t\t\t\t\tif ($('#roleGrid').datagrid('getChanges').length) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar deleted = $('#roleGrid').datagrid('getChanges',\"deleted\");\r\n");
      out.write("\t\t\t\t\t\tvar effectRow = new Object();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif (deleted.length) {\r\n");
      out.write("\t\t\t\t\t\t\teffectRow[\"deleted\"] = JSON.stringify(deleted);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.post(\t$('#webContext').attr('value')+ '/rest/DrpUser/delRole/'+selectUserID,effectRow,function(rsp) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//if (rsp.status) {\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t$('#roleGrid').datagrid('acceptChanges');\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//}\r\n");
      out.write("\t\t\t\t\t\t},'text').error(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交错误了！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar rows = $('#roleGrid').datagrid('getRows');\r\n");
      out.write("\t\t\t\t\t\tfor ( var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t$('#roleGrid').datagrid('endEdit', $('#roleGrid').datagrid('getRowIndex',rows[i]));\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t});\r\n");
      out.write("   \t\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t$('#roleGridNo').datagrid({\r\n");
      out.write("\t\t\ttitle : '未分配角色',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\theight : 350,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tautoRowHeight : false,\r\n");
      out.write("\t\t\tstriped : true,\r\n");
      out.write("\t\t\tcollapsible : true,\r\n");
      out.write("\t\t\turl :  $('#webContext').attr('value')+'/rest/DrpUser/queryRoleNoGrant/-1',\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\tremoteSort : false,\r\n");
      out.write("\t\t\tidField:'roleid',\r\n");
      out.write("\t\t\tcolumns : [ [\r\n");
      out.write("\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfield : 'roleid',\r\n");
      out.write("\t\t\t\ttitle : '主键',\r\n");
      out.write("\t\t\t\thidden : true\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'rolename',\r\n");
      out.write("\t\t\t\ttitle : '角色名称',\r\n");
      out.write("\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'roledesc',\r\n");
      out.write("\t\t\t\ttitle : '角色描述',\r\n");
      out.write("\t\t\t\twidth :200,\r\n");
      out.write("\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t] ],\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\r\n");
      out.write("\t\t\ttoolbar : [{\r\n");
      out.write("\t\t\t\tid : 'btnsave',\r\n");
      out.write("\t\t\t\ttext : '保存',\r\n");
      out.write("\t\t\t\tdisabled : false,\r\n");
      out.write("\t\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t$('#btnsave').linkbutton('disable');\r\n");
      out.write("\t\t\t\t\tvar selectedRows = $('#roleGridNo').datagrid('getSelections');\r\n");
      out.write("\t\t\t\t\tif (selectedRows.length>0) {\r\n");
      out.write("\t\t\t\t\t\tvar roleidStr='-1';\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar effectRow = new Object();\r\n");
      out.write("\t\t\t\t\t\teffectRow[\"grant\"] = JSON.stringify(selectedRows);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.post(\t$('#webContext').attr('value')+ '/rest/DrpUser/addRole/'+selectUserID+'/'+roleidStr,effectRow,function(rsp) {\r\n");
      out.write("\t\t\t\t\t\t\tif(rsp=='1'){\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#roleGridNo').datagrid('options').url = $('#webContext').attr('value')+'/rest/DrpUser/queryRoleNoGrant/'+selectUserID;\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#roleGridNo').datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#roleGrid').datagrid('options').url = $('#webContext').attr('value')+'/rest/DrpUser/queryrole/'+selectUserID;\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#roleGrid').datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//}\r\n");
      out.write("\t\t\t\t\t\t},'text').error(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交错误了！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t});\r\n");
      out.write("   \t\r\n");
      out.write("   \t\r\n");
      out.write("   \t});  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction addChildren(node){\r\n");
      out.write("\t\t\tvar usergroup =  node.id;\r\n");
      out.write("\t\t\tvar para = new Object();\r\n");
      out.write("\t\t\tpara['usergroup']=usergroup;\r\n");
      out.write("\t\t\t$.post(\t$('#webContext').attr('value')+ '/rest/DrpUser/get/usergroup',para,function(rsp) {\r\n");
      out.write("\t\t\t\tvar datas = eval(\"(\" + rsp + \")\");\r\n");
      out.write("\t\t\t\t//$('#tt2').tree('remove',node.target);\r\n");
      out.write("\t\t\t\t$('#tt2').tree('append',{\r\n");
      out.write("\t\t\t\tparent: node.target,\r\n");
      out.write("\t\t\t\tdata:datas\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#tt2\").tree('expand', node.target);\r\n");
      out.write("\t\t\t\t\t\t}, \"text\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.error(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交错误了！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction initTree(){\r\n");
      out.write("\t\t\tvar para = new Object();\r\n");
      out.write("\t\t\t$.post(\t$('#webContext').attr('value')+ '/rest/DrpDept/get/all',para,function(rsp) {\r\n");
      out.write("\t\t\t\tvar datas = eval(\"(\" + rsp + \")\");\r\n");
      out.write("\t\t\t\t//$('#tt2').tree('remove',node.target);\r\n");
      out.write("\t\t\t\t$(\"#tt2\").tree({  \r\n");
      out.write("               \t\tdata : datas,\r\n");
      out.write("           \t\t\tonClick: function(node){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar children = $(this).tree('getChildren', node.target);\r\n");
      out.write("\t\t\t\t\t\t\t\tselectUserID = node.id;\r\n");
      out.write("\t\t\t\t\t\t\t\tif(children.length==0){\r\n");
      out.write("\t\t\t\t\t\t\t\t\taddChildren(node);\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).tree('toggle', node.target);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tqueryRoleByUser(selectUserID);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tonContextMenu: function(e,node){\r\n");
      out.write("\t\t\t\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).tree('select',node.target);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#mm').menu('show',{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tleft: e.pageX,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttop: e.pageY\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("           \t\t}); \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}, \"text\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.error(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交错误了！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//---------------弹出窗口\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction queryRoleByUser(userID){\r\n");
      out.write("\t\t\t$('#roleGrid').datagrid('options').url=$('#webContext').attr('value')+'/rest/DrpUser/queryrole/'+userID;\r\n");
      out.write("\t\t\t$('#roleGrid').datagrid('load');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction openRoleHidden(){\r\n");
      out.write("\t\t\t$('#roleHidden').window('open');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type=\"hidden\" id=\"webContext\" value=\"");
      out.print(webContext);
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div style=\"position:absolute; left:10px; top:0px;width:400px;height:100%;border:1px solid #ccc;overflow:auto;\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<ul id=\"tt2\"></ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div style=\"position:absolute; left: 420px;top: 0px\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<table id=\"roleGrid\"></table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"roleHidden\" class=\"easyui-window\" data-options=\"closed:true,modal:true,title:'Test Window'\" style=\"width:600px;height:300px;\">\r\n");
      out.write("\t\t<table id=\"roleGridNo\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
