package org.apache.jsp.authority;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rolemanage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String webContext = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>成衣维修操作列表</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<title>角色管理</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\thref=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/themes/default/easyui.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\thref=\"");
      out.print(webContext);
      out.write("/css/cmcommon.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\thref=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/demo/demo.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\t\thref=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/themes/icon.css\">\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.print(webContext);
      out.write("/jquery-easyui-1.3.1/src/jquery.parser.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tvar selectedRoleID;\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#roleGrid').datagrid({\r\n");
      out.write("\t\t\ttitle : '角色',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\theight : 350,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tautoRowHeight : false,\r\n");
      out.write("\t\t\tstriped : true,\r\n");
      out.write("\t\t\tcollapsible : true,\r\n");
      out.write("\t\t\turl :  $('#webContext').attr('value')+'/rest/queryRole/all',\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\tremoteSort : false,\r\n");
      out.write("\t\t\tsingleSelect: true,\r\n");
      out.write("\t\t\tidField:'roleid',\r\n");
      out.write("\t\t\tcolumns : [ [\r\n");
      out.write("\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfield : 'roleid',\r\n");
      out.write("\t\t\t\ttitle : '主键',\r\n");
      out.write("\t\t\t\thidden : true\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'rolename',\r\n");
      out.write("\t\t\t\ttitle : '角色名称',\r\n");
      out.write("\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\tsortable : true,\r\n");
      out.write("\t\t\t\teditor : \"validatebox\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'roledesc',\r\n");
      out.write("\t\t\t\ttitle : '角色描述',\r\n");
      out.write("\t\t\t\twidth :200,\r\n");
      out.write("\t\t\t\tsortable : true,\r\n");
      out.write("\t\t\t\teditor : \"validatebox\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t] ],\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tonClickRow: function (rowIndex) {\r\n");
      out.write("\t\t\t\tqueryMenu();\r\n");
      out.write("\t\t\t}, \r\n");
      out.write("\r\n");
      out.write("\t\t\ttoolbar : [ {\r\n");
      out.write("\t\t\t\tid : 'btnadd',\r\n");
      out.write("\t\t\t\ttext : '新增',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t$('#btnsave').linkbutton('enable');\r\n");
      out.write("\t\t\t\t\t$('#roleGrid').datagrid('appendRow', {id:'',rolename:'',roledesc:''});\r\n");
      out.write("\t\t\t\t\tvar rows = $('#roleGrid').datagrid('getRows');\r\n");
      out.write("\t\t\t\t\t$('#roleGrid').datagrid('beginEdit', rows.length - 1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{id: 'btnedit',\r\n");
      out.write("\t\t\t\ttext : \"编辑\",\r\n");
      out.write("\t\t\t\ticonCls : \"icon-edit\",\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t$('#btnsave').linkbutton('enable');\r\n");
      out.write("\t\t\t\t\tvar row = $('#roleGrid').datagrid('getSelected');\r\n");
      out.write("\t\t\t\t\tif (row) {\r\n");
      out.write("\t\t\t\t\t var rowIndex = $('#roleGrid').datagrid('getRowIndex', row);\r\n");
      out.write("\t\t\t\t\t $('#roleGrid').datagrid('beginEdit', rowIndex);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\t\t\t\r\n");
      out.write("\t\t\t}, \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tid : 'btncut',\r\n");
      out.write("\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-cut',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t$('#btnsave').linkbutton('enable');\r\n");
      out.write("\t\t\t\t\tvar row = $('#roleGrid').datagrid('getSelected');\r\n");
      out.write("\t\t\t\t\tif (row) { \r\n");
      out.write("\t\t\t\t\t\tvar rowIndex = $('#roleGrid').datagrid('getRowIndex', row);\r\n");
      out.write("\t\t\t\t\t\t$('#roleGrid').datagrid('deleteRow', rowIndex);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, '-', {\r\n");
      out.write("\t\t\t\tid : 'btnsave',\r\n");
      out.write("\t\t\t\ttext : '保存',\r\n");
      out.write("\t\t\t\tdisabled : true,\r\n");
      out.write("\t\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t$('#btnsave').linkbutton('disable');\r\n");
      out.write("\t\t\t\t\tendEdit();\r\n");
      out.write("\t\t\t\t\tif ($('#roleGrid').datagrid('getChanges').length) {\r\n");
      out.write("\t\t\t\t\t\tvar inserted = $('#roleGrid').datagrid('getChanges',\"inserted\");\r\n");
      out.write("\t\t\t\t\t\tvar deleted = $('#roleGrid').datagrid('getChanges',\"deleted\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar updated = $('#roleGrid').datagrid('getChanges',\"updated\");\r\n");
      out.write("\t\t\t\t\t\tvar effectRow = new Object();\r\n");
      out.write("\t\t\t\t\t\tif (inserted.length) {\r\n");
      out.write("\t\t\t\t\t\t\teffectRow[\"inserted\"] = JSON.stringify(inserted);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (deleted.length) {\r\n");
      out.write("\t\t\t\t\t\t\teffectRow[\"deleted\"] = JSON.stringify(deleted);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (updated.length) {\r\n");
      out.write("\t\t\t\t\t\t\teffectRow[\"updated\"] = JSON.stringify(updated);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.post(\t$('#webContext').attr('value')+ '/rest/roleChange',effectRow,function(rsp) {\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t$('#roleGrid').datagrid('acceptChanges');\r\n");
      out.write("\t\t\t\t\t\t\tqueryRole();\r\n");
      out.write("\t\t\t\t\t\t},'text').error(function() {$.messager.alert(\"提示\",\"提交错误了！\");\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar rows = $('#roleGrid').datagrid('getRows');\r\n");
      out.write("\t\t\t\t\t\tfor ( var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t$('#roleGrid').datagrid('endEdit', i);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar p = $('#roleGrid').datagrid('getPager');\r\n");
      out.write("\t\t$(p).pagination({\r\n");
      out.write("\t\t\tonSelectPage: function( pageNumber, pageSize ) {\r\n");
      out.write("\t\t\t\tvar grid = $('#datagrid');  \r\n");
      out.write("\t\t\t\tvar options = grid.datagrid('getPager').data(\"pagination\").options;  \r\n");
      out.write("\t\t\t\tvar curr = options.pageNumber;  \r\n");
      out.write("\t\t\t\tvar total = options.total;  \r\n");
      out.write("\t\t\t\tvar max = Math.ceil(total/options.pageSize);  \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonBeforeRefresh : function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\talert('before refresh');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction endEdit(){\r\n");
      out.write("           \t\tvar rows = $('#roleGrid').datagrid('getRows');\r\n");
      out.write("           \t\t for ( var i = 0; i < rows.length; i++) {\r\n");
      out.write("                \t$('#roleGrid').datagrid('endEdit', i);\r\n");
      out.write("           \t\t }\r\n");
      out.write("        \t};\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#menuGrid').datagrid({\r\n");
      out.write("\t\t\t\t\t\t\ttitle : '菜单',\r\n");
      out.write("\t\t\t\t\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\t\t\t\theight : 350,\r\n");
      out.write("\t\t\t\t\t\t\tnowrap : true,\r\n");
      out.write("\t\t\t\t\t\t\tautoRowHeight : false,\r\n");
      out.write("\t\t\t\t\t\t\tstriped : true,\r\n");
      out.write("\t\t\t\t\t\t\tcollapsible : true,\r\n");
      out.write("\t\t\t\t\t\t\turl : $('#webContext').attr('value') + '/rest/queryMenu/id/-1',\r\n");
      out.write("\t\t\t\t\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\t\t\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\t\t\t\t\tremoteSort : false,\r\n");
      out.write("\t\t\t\t\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\t\t\t\t\tfield : 'menuid',\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '主键',\r\n");
      out.write("\t\t\t\t\t\t\t\thidden : true\r\n");
      out.write("\t\t\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\t\t\tfield : 'menuname',\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '菜单名',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth : 300,\r\n");
      out.write("\t\t\t\t\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t\t\t\t\t} ] ],\r\n");
      out.write("\t\t\t\t\t\t\tpagination : true,\r\n");
      out.write("\t\t\t\t\t\t\trownumbers : true,\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\ttoolbar : [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid : 'btnadd',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : '新增',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tselectedRoleID = $('#roleGrid').datagrid('getSelected').roleid;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif(selectedRoleID==null || selectedRoleID==''){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talert('必须选择角色');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('#menuGridNo').datagrid('options').url = $('#webContext').attr('value')+'/rest/queryMenu/notGrant/id/'+selectedRoleID;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('#menuGridNo').datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\topenRoleHidden();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid : 'btncut',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : 'icon-cut',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$('#btnsave').linkbutton('enable');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar row = $('#menuGrid').datagrid('getSelected');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (row) { \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar rowIndex = $('#menuGrid').datagrid('getRowIndex', row);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$('#menuGrid').datagrid('deleteRow', rowIndex);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'-',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid : 'btnsave',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttext : '保存',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdisabled : false,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//$('#btnsave').linkbutton('disable');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tendEdit();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif ($('#menuGrid').datagrid('getChanges').length) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar deleted = $('#menuGrid').datagrid('getChanges',\"deleted\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar effectRow = new Object();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (deleted.length) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\teffectRow[\"deleted\"] = JSON.stringify(deleted);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tselectedRoleID = $('#roleGrid').datagrid('getSelected').roleid;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$.post(\t$('#webContext').attr('value')+ '/rest/delMenu/id/'+selectedRoleID,effectRow,function(rsp) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(rsp);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (rsp=='1') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('#menuGrid').datagrid('acceptChanges');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}, \"JSON\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.error(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交错误了！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar p = $('#menuGrid').datagrid('getPager');\r\n");
      out.write("\t\t$(p).pagination({\r\n");
      out.write("\t\t\tonSelectPage: function( pageNumber, pageSize ) {\r\n");
      out.write("\t\t\t\talert(pageSize);\r\n");
      out.write("\t\t\t\tvar grid = $('#datagrid');  \r\n");
      out.write("\t\t\t\tvar options = grid.datagrid('getPager').data(\"pagination\").options;  \r\n");
      out.write("\t\t\t\tvar curr = options.pageNumber;  \r\n");
      out.write("\t\t\t\tvar total = options.total;  \r\n");
      out.write("\t\t\t\tvar max = Math.ceil(total/options.pageSize);  \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonBeforeRefresh : function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\talert('before refresh');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('#menuGridNo').datagrid({\r\n");
      out.write("\t\t\ttitle : '未分配菜单',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\theight : 350,\r\n");
      out.write("\t\t\tnowrap : true,\r\n");
      out.write("\t\t\tautoRowHeight : false,\r\n");
      out.write("\t\t\tstriped : true,\r\n");
      out.write("\t\t\tcollapsible : true,\r\n");
      out.write("\t\t\turl :  $('#webContext').attr('value')+'/rest/queryMenu/notGrant/id/-1',\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tsortOrder : 'desc',\r\n");
      out.write("\t\t\tremoteSort : false,\r\n");
      out.write("\t\t\tidField:'menuid',\r\n");
      out.write("\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\t\t\t\t\tfield : 'menuid',\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '主键',\r\n");
      out.write("\t\t\t\t\t\t\t\thidden : true\r\n");
      out.write("\t\t\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\t\t\tfield : 'menuname',\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '菜单名',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth : 300,\r\n");
      out.write("\t\t\t\t\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t\t\t\t\t} ] ],\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\r\n");
      out.write("\t\t\ttoolbar : [{\r\n");
      out.write("\t\t\t\tid : 'btnsave',\r\n");
      out.write("\t\t\t\ttext : '保存',\r\n");
      out.write("\t\t\t\tdisabled : false,\r\n");
      out.write("\t\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//$('#btnsave').linkbutton('disable');\r\n");
      out.write("\t\t\t\t\tvar selectedRows = $('#menuGridNo').datagrid('getSelections');\r\n");
      out.write("\t\t\t\t\tif (selectedRows.length>0) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar roleidStr='-1';\r\n");
      out.write("\t\t\t\t\t\t/*for(var i=0;i<=selectedRows.length;i++){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\troleidStr = roleidStr+\",\"+selectedRows[i].menuid;\r\n");
      out.write("\t\t\t\t\t\t\talert(selectedRows[i].menuid);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\talert('1111');\r\n");
      out.write("\t\t\t\t\t\troleidStr = roleidStr.substring(1,3);*/\r\n");
      out.write("\t\t\t\t\t\t//alert(JSON.stringify(selectedRows));\r\n");
      out.write("\t\t\t\t\t\tvar effectRow = new Object();\r\n");
      out.write("\t\t\t\t\t\teffectRow[\"grant\"] = JSON.stringify(selectedRows);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.post(\t$('#webContext').attr('value')+ '/rest/addMenu/id/'+selectedRoleID+'/'+roleidStr,effectRow,function(rsp) {\r\n");
      out.write("\t\t\t\t\t\t\tif(rsp=='1'){\r\n");
      out.write("\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#menuGridNo').datagrid('options').url = $('#webContext').attr('value')+'/rest/queryMenu/notGrant/id/'+selectedRoleID;\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#menuGridNo').datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#menuGrid').datagrid('options').url = $('#webContext').attr('value')+'/rest/queryMenu/id/'+selectedRoleID;\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#menuGrid').datagrid('load');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//}\r\n");
      out.write("\t\t\t\t\t\t},'text').error(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"提示\",\"提交错误了！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction queryRole() {\r\n");
      out.write("\t\tvar roleName = $('#roleName').attr('value');\r\n");
      out.write("\t\tif (roleName != '' && roleName != null) {\r\n");
      out.write("\t\t\talert(roleName);\r\n");
      out.write("\t\t\t$('#roleGrid').datagrid('options').url = $('#webContext').attr('value')\r\n");
      out.write("\t\t\t\t\t+ '/rest/queryRole/name/' + roleName;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$('#roleGrid').datagrid('options').url = $('#webContext').attr('value')\r\n");
      out.write("\t\t\t\t\t+ '/rest/queryRole/all';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('#roleGrid').datagrid('load');\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction queryMenu() {\r\n");
      out.write("\t\tvar selected = $('#roleGrid').datagrid('getSelected');\r\n");
      out.write("\t\tvar roleid = selected.roleid;\r\n");
      out.write("\t\t$('#menuGrid').datagrid('options').url = $('#webContext').attr('value')\r\n");
      out.write("\t\t\t\t+ '/rest/queryMenu/id/' + roleid;\r\n");
      out.write("\t\t$('#menuGrid').datagrid('load');\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction saveChangeData() {\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//---------------弹出窗口\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction openRoleHidden(){\r\n");
      out.write("\t\t\t$('#menuHidden').window('open');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"webContext\" value=\"");
      out.print(webContext);
      out.write("\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style=\"position:relative;width:100%;height:100%;border:1px solid #ccc;overflow:auto;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div data-options=\"region:'west',split:true\" title=\"角色\"\r\n");
      out.write("\t\t\tstyle=\"width: 800px; padding1: 1px; overflow: hidden;\">\r\n");
      out.write("\t\t\t<div class=\"easyui-accordion\" data-options=\"fit:true,border:false\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t角色名：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"roleName\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" id=\"button1\" value=\"查询\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"queryRole()\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table width=\"800\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"400\">\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'center'\" title=\"角色管理\" style=\"overflow: hidden;\">\r\n");
      out.write("\t\t\t\t\t<table id=\"roleGrid\"></table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"400\">\r\n");
      out.write("\t\t\t<div data-options=\"region:'center'\" title=\"菜单\"\t style=\"overflow: hidden;\" >\r\n");
      out.write("\t\t\t\t<table id=\"menuGrid\"></table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"menuHidden\" class=\"easyui-window\" data-options=\"closed:true,modal:true,title:'Test Window'\" style=\"width:600px;height:300px;\">\r\n");
      out.write("\t\t<table id=\"menuGridNo\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
