/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-06-2011
 * 
 * XDoclet definition:
 * @struts.form name="appraiseinfForm"
 */
public class AppraiseinfoForm extends CloMaintenanceForm {
	
	private String updateSuccessFlag;
	/*
	 * Generated Methods
	 */

	public String getUpdateSuccessFlag() {
		return updateSuccessFlag;
	}

	public void setUpdateSuccessFlag(String updateSuccessFlag) {
		this.updateSuccessFlag = updateSuccessFlag;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}