/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-29-2012
 * 
 * XDoclet definition:
 * @struts.form name="customerPrintForm"
 */
public class CustomerPrintForm extends CloMaintenanceForm {
}