/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2011
 * 
 * XDoclet definition:
 * @struts.form name="eidtMaintenanceBillForm"
 */
public class EidtMaintenanceBillForm extends CloMaintenanceForm {
	private String dpTypeName;
	private String dpTypeCode;
	private FormFile uploadFile;
	private String isSaveFlag;
	private String picGuid;
	private String ztTypeName="登记";
	private String sldgCode;
	private String picms;
	private String saveState;
	
	
	
	public String getSaveState() {
		return saveState;
	}
	public void setSaveState(String saveState) {
		this.saveState = saveState;
	}
	public String getPicms() {
		return picms;
	}
	public void setPicms(String picms) {
		this.picms = picms;
	}
	public String getSldgCode() {
		return sldgCode;
	}
	public void setSldgCode(String sldgCode) {
		this.sldgCode = sldgCode;
	}
	public String getZtTypeName() {
		return ztTypeName;
	}
	public void setZtTypeName(String ztTypeName) {
		this.ztTypeName = ztTypeName;
	}
	public String getPicGuid() {
		return picGuid;
	}
	public void setPicGuid(String picGuid) {
		this.picGuid = picGuid;
	}

	public String getIsSaveFlag() {
		return isSaveFlag;
	}
	public void setIsSaveFlag(String isSaveFlag) {
		this.isSaveFlag = isSaveFlag;
	}
	public FormFile getUploadFile() {
		return uploadFile;
	}
	public void setUploadFile(FormFile uploadFile) {
		this.uploadFile = uploadFile;
	}
	public String getDpTypeName() {
		return dpTypeName;
	}
	public void setDpTypeName(String dpTypeName) {
		this.dpTypeName = dpTypeName;
	}
	public String getDpTypeCode() {
		return dpTypeCode;
	}
	public void setDpTypeCode(String dpTypeCode) {
		this.dpTypeCode = dpTypeCode;
	}
}