/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.form;

/** 
 * MyEclipse Struts
 * Creation date: 09-27-2011
 * 
 * XDoclet definition:
 * @struts.form name="maintenanceInfoListForm"
 */
public class MaintenanceInfoListForm extends CloMaintenanceForm {
	private String isShop;//
	private String czlx;
	private String operateBgnDate;
	private String operateEndDate;
	private String judgeBgnDate;
	private String advancedCondition="0";
	public String getAdvancedCondition() {
		return advancedCondition;
	}
	public void setAdvancedCondition(String advancedCondition) {
		this.advancedCondition = advancedCondition;
	}
	public String getIsShop() {
		return isShop;
	}
	public void setIsShop(String isShop) {
		this.isShop = isShop;
	}
	public String getCzlx() {
		return czlx;
	}
	public void setCzlx(String czlx) {
		this.czlx = czlx;
	}
	public String getOperateBgnDate() {
		return operateBgnDate;
	}
	public void setOperateBgnDate(String operateBgnDate) {
		this.operateBgnDate = operateBgnDate;
	}
	public String getOperateEndDate() {
		return operateEndDate;
	}
	public void setOperateEndDate(String operateEndDate) {
		this.operateEndDate = operateEndDate;
	}
	public String getJudgeBgnDate() {
		return judgeBgnDate;
	}
	public void setJudgeBgnDate(String judgeBgnDate) {
		this.judgeBgnDate = judgeBgnDate;
	}
	public String getJudgeEndDate() {
		return judgeEndDate;
	}
	public void setJudgeEndDate(String judgeEndDate) {
		this.judgeEndDate = judgeEndDate;
	}
	private String judgeEndDate;
}