/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.form;

/** 
 * MyEclipse Struts
 * Creation date: 10-07-2011
 * 
 * XDoclet definition:
 * @struts.form name="shopPrintForm"
 */
public class ShopPrintForm extends CloMaintenanceForm {
	
}