/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.form;


/** 
 * MyEclipse Struts
 * Creation date: 10-17-2011
 * 
 * XDoclet definition:
 * @struts.form name="shopLogisticsBillForm"
 */
public class ShopLogisticsBillForm extends CloMaintenanceForm {
	
}