/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2011
 * 
 * XDoclet definition:
 * @struts.form name="viewMaintenanceBillFormForm"
 */
public class ViewMaintenanceBillForm extends CloMaintenanceForm {
	private String ztTypeName;
	private String dpTypeName;
	private String dpTypeCode;
	
	
	/*
	 * Generated Methods
	 */
	
	

	public String getDpTypeCode() {
		return dpTypeCode;
	}

	public void setDpTypeCode(String dpTypeCode) {
		this.dpTypeCode = dpTypeCode;
	}

	public String getZtTypeName() {
		return ztTypeName;
	}

	public String getDpTypeName() {
		return dpTypeName;
	}

	public void setDpTypeName(String dpTypeName) {
		this.dpTypeName = dpTypeName;
	}

	public void setZtTypeName(String ztTypeName) {
		this.ztTypeName = ztTypeName;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}