USE [epapp]
GO

/****** Object:  Table [dbo].[CM_REL_ROLEMENU]    Script Date: 12/15/2012 16:39:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CM_REL_ROLEMENU](
	[roleid] [int] NOT NULL,
	[menuid] [int] NOT NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CM_REL_ROLEMENU]  WITH CHECK ADD  CONSTRAINT [FK_CM_REL_ROLEMENU_CM_MENU] FOREIGN KEY([menuid])
REFERENCES [dbo].[CM_MENU] ([menuid])
GO

ALTER TABLE [dbo].[CM_REL_ROLEMENU] CHECK CONSTRAINT [FK_CM_REL_ROLEMENU_CM_MENU]
GO

ALTER TABLE [dbo].[CM_REL_ROLEMENU]  WITH CHECK ADD  CONSTRAINT [FK_CM_REL_ROLEMENU_CM_ROLE] FOREIGN KEY([roleid])
REFERENCES [dbo].[CM_ROLE] ([roleid])
GO

ALTER TABLE [dbo].[CM_REL_ROLEMENU] CHECK CONSTRAINT [FK_CM_REL_ROLEMENU_CM_ROLE]
GO


