/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import ep.org.clothingmaintenance.bean.MaintenanceBill;
import ep.org.clothingmaintenance.bean.UserInfo;
import ep.org.clothingmaintenance.form.AppraiseinfoForm;
import ep.org.clothingmaintenance.service.CloMaintenanceService;

/** 
 * MyEclipse Struts
 * Creation date: 10-06-2011
 * 
 * XDoclet definition:
 * @struts.action path="/appraiseinfo" name="appraiseinfoForm" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="toAppraiseInfo" path="/colmaintenance/appraiseinfo.jsp"
 */
public class AppraiseinfoAction extends DispatchAction {
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		String loginDeptID =request.getParameter("loginDeptID"); 
		String userID =request.getParameter("userID"); 
		AppraiseinfoForm infoForm = (AppraiseinfoForm) form;
		infoForm.setLoginDeptID(loginDeptID);
		infoForm.setUserID(userID);
		return mapping.findForward("toAppraiseInfo");
	}
	
	public ActionForward viewAppraiseinfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		AppraiseinfoForm infoForm = (AppraiseinfoForm) form;
		infoForm.setGuid(request.getParameter("guid"));
		String userID =request.getParameter("userID"); 
		CloMaintenanceService service = new CloMaintenanceService();
		MaintenanceBill bean = (MaintenanceBill) service.viewAppraiseinfo(infoForm.getGuid());
		infoForm.setUserID(userID);
		infoForm.setZT(bean.getZT());
		infoForm.setGKPJ(bean.getGKPJ());
		infoForm.setGKPJYJ(bean.getGKPJYJ());
		infoForm.setDPPJ(bean.getDPPJ());
		infoForm.setDPPJYJ(bean.getDPPJYJ());
		
		return mapping.findForward("toAppraiseInfo");
	}

	public ActionForward updateAppraise(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		AppraiseinfoForm infoForm = (AppraiseinfoForm) form;
		MaintenanceBill bean = new MaintenanceBill();
		UserInfo userInfo = (UserInfo) request.getSession().getAttribute("user_info");
		bean.setUserid(infoForm.getUserID());
		bean.setDpbm(infoForm.getDpbm());
		bean.setGuid(infoForm.getGuid());
		bean.setGKPJ(infoForm.getGKPJ());
		bean.setGKPJYJ(infoForm.getGKPJYJ());
		bean.setDPPJ(infoForm.getDPPJ());
		bean.setDPPJYJ(infoForm.getDPPJYJ());
		bean.setZT(infoForm.getZT());
		CloMaintenanceService service = new CloMaintenanceService();
		service.updateAppraise(bean,userInfo);
		infoForm.setUpdateSuccessFlag("1");
		
		return mapping.findForward("toAppraiseInfo");
	}
}