/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import ep.org.clothingmaintenance.bean.MaintenanceBill;
import ep.org.clothingmaintenance.form.ExpressWayBillForm;
import ep.org.clothingmaintenance.service.CloMaintenanceService;

/** 
 * MyEclipse Struts
 * Creation date: 10-07-2011
 * 
 * XDoclet definition:
 * @struts.action path="/expressWayBill" name="expressWayBillForm" parameter="method" scope="request"
 * @struts.action-forward name="toExpressWayBill" path="/colmaintenance/expressWayBill.jsp"
 */
public class ExpressWayBillAction extends DispatchAction {
	public ActionForward getExpressData(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String guid = request.getParameter("guid");
		ExpressWayBillForm billForm = (ExpressWayBillForm)form;
		billForm.setGuid(guid);
		CloMaintenanceService service = new CloMaintenanceService();
		MaintenanceBill bean = (MaintenanceBill) service.getExpressData(guid);
		billForm.setSHR(bean.getSHR());
		billForm.setDZXM(bean.getDZXM());
		billForm.setDZLXDH(bean.getDZLXDH());
		billForm.setDpmc(bean.getDpmc());
		billForm.setFHDZ(bean.getFHDZ());
		billForm.setSHDZ(bean.getSHDZ());
		billForm.setSHRLXDH(bean.getSHRLXDH());
		
		return mapping.findForward("toExpressWayBill");
	}
}