/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import ep.org.clothingmaintenance.service.CloMaintenanceService;

/** 
 * MyEclipse Struts
 * Creation date: 10-06-2011
 * 
 * XDoclet definition:
 * @struts.action path="/operaterecord" name="operaterecordForm" parameter="method" scope="request"
 * @struts.action-forward name="toOperateRecord" path="/colmaintenance/operaterecord.jsp"
 */
public class OperaterecordAction extends DispatchAction {
	
	public ActionForward query(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		String guid = request.getParameter("guid");
		CloMaintenanceService service = new CloMaintenanceService();
		request.setAttribute("recordlist", service.queryOperateRecord(guid));
		return mapping.findForward("toOperateRecord");
	}

}