/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import ep.org.clothingmaintenance.bean.MaintenanceBill;
import ep.org.clothingmaintenance.form.ShopPrintForm;
import ep.org.clothingmaintenance.service.CloMaintenanceService;

/** 
 * MyEclipse Struts
 * Creation date: 10-07-2011
 * 
 * XDoclet definition:
 * @struts.action path="/shopPrint" name="shopPrintForm" parameter="method" scope="request"
 * @struts.action-forward name="toShopPrint" path="/colmaintenance/shopPrint.jsp"
 */
public class ShopPrintAction extends DispatchAction{
	public ActionForward getShopPrintData(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String guid = request.getParameter("guid");
		ShopPrintForm shopPrintForm = (ShopPrintForm)form;
		shopPrintForm.setGuid(guid);
		CloMaintenanceService service = new CloMaintenanceService();
		MaintenanceBill bean = (MaintenanceBill) service.getShopPrintData(guid);
		
		shopPrintForm.setDh(bean.getDh());
		shopPrintForm.setPP(bean.getPP());
		shopPrintForm.setDpmc(bean.getDpmc());
		shopPrintForm.setGKWX(bean.getGKWX());
		shopPrintForm.setDZXM(bean.getDZXM());
		shopPrintForm.setGKXM(bean.getGKXM());
		shopPrintForm.setGKLXDH(bean.getGKLXDH());
		shopPrintForm.setWXCBM(bean.getWXCBM());
		shopPrintForm.setVIPKH(bean.getVIPKH());
		shopPrintForm.setSLDG(bean.getSLDG());
		shopPrintForm.setSFTYFFWX(bean.getSFTYFFWX());
		shopPrintForm.setKH(bean.getKH());
		shopPrintForm.setYS(bean.getYS());
		shopPrintForm.setMS(bean.getMS());
		shopPrintForm.setSCSJ(bean.getSCSJ());
		shopPrintForm.setWTMS(bean.getWTMS());
		shopPrintForm.setYSGS(bean.getYSGS());
		shopPrintForm.setYDH(bean.getYDH());
		shopPrintForm.setFHDZ(bean.getFHDZ());
		shopPrintForm.setTHRQ(bean.getTHRQ());
		shopPrintForm.setDZLXDH(bean.getDZLXDH());
		
		return mapping.findForward("toShopPrint");
	}

}