/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import ep.org.clothingmaintenance.bean.MaintenanceBill;
import ep.org.clothingmaintenance.form.HQSendGoodsForm;
import ep.org.clothingmaintenance.service.CloMaintenanceService;
/** 
 * MyEclipse Struts
 * Creation date: 10-05-2011
 * 
 * XDoclet definition:
 * @struts.action path="/viewHQSendGoods" name="HQSendGoodsForm" parameter="method" scope="request"
 * @struts.action-forward name="viewHQSendGoods" path="/colmaintenance/HQsendgoods.jsp"
 */
public class ViewHQSendGoodsAction extends DispatchAction {
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		String loginDeptID =request.getParameter("loginDeptID"); 
		String userID =request.getParameter("userID"); 
		HQSendGoodsForm viewForm = (HQSendGoodsForm) form;
		viewForm.setLoginDeptID(loginDeptID);
		viewForm.setUserID(userID);
		return mapping.findForward("viewHQSendGoods");
	}
	
	public ActionForward viewHQSendGoods(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		HQSendGoodsForm viewForm = (HQSendGoodsForm) form;
		viewForm.setGuid(request.getParameter("guid"));
		CloMaintenanceService service = new CloMaintenanceService();
		MaintenanceBill bean =  (MaintenanceBill) service.viewHQSendGoods(viewForm.getGuid());
		viewForm.setZBFH_DH(bean.getZBFH_DH());
		viewForm.setZBFH_YSGS(bean.getZBFH_YSGS());
		viewForm.setZBFH_FHDZ(bean.getZBFH_FHDZ());
		viewForm.setZBFH_YSDH(bean.getZBFH_YSDH());
		viewForm.setZBFH_SHDZ(bean.getZBFH_SHDZ());
		viewForm.setZBFH_SHR(bean.getZBFH_SHR());
		viewForm.setZBFH_SHRDH(bean.getZBFH_SHRDH());
		viewForm.setZBFH_BZ(bean.getZBFH_BZ());
		viewForm.setZBFH_BZR(bean.getZBFH_BZR());
		viewForm.setZBFH_BZSJ(bean.getZBFH_BZSJ());
		viewForm.setDpbm(bean.getDpbm());
		viewForm.setDpmc(bean.getDpmc());
		
		
		return mapping.findForward("viewHQSendGoods");
	}
}