/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package ep.org.clothingmaintenance.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import ep.org.clothingmaintenance.bean.MaintenanceBill;
import ep.org.clothingmaintenance.form.ViewMaintenanceBillForm;
import ep.org.clothingmaintenance.service.CloMaintenanceService;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2011
 * 
 * XDoclet definition:
 * @struts.action path="/viewMaintenanceBill" name="viewMaintenanceBillFormForm" parameter="method" scope="request"
 * @struts.action-forward name="viewMaintenanceInfo" path="/colmaintenance/maintenanceParticularInfo.jsp"
 */
public class ViewMaintenanceBillAction extends DispatchAction {
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		String loginDeptID =request.getParameter("loginDeptID"); 
		String userID =request.getParameter("userID"); 
		ViewMaintenanceBillForm viewForm = (ViewMaintenanceBillForm) form;
		viewForm.setLoginDeptID(loginDeptID);
		viewForm.setUserID(userID);
		
		
		return mapping.findForward("viewMaintenanceInfo");
	}
	
	
	public ActionForward viewInfo(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		
		ViewMaintenanceBillForm viewForm = (ViewMaintenanceBillForm) form;
		viewForm.setGuid(request.getParameter("guid"));
		CloMaintenanceService service = new CloMaintenanceService();
		MaintenanceBill bean = (MaintenanceBill) service.viewMaintenanceBillInfo(viewForm.getGuid());
		viewForm.setGuid(bean.getGuid());
		viewForm.setZtTypeName(bean.getZtTypeName());
		viewForm.setDh(bean.getDh());
		viewForm.setDpbm(bean.getDpbm());
		viewForm.setDpmc(bean.getDpmc());
		viewForm.setDplx(bean.getDplx());
		viewForm.setDZXM(bean.getDZXM());
		viewForm.setDZLXDH(bean.getDZLXDH());
		viewForm.setWXCBM(bean.getWXCBM());
		viewForm.setWXCMC(bean.getWXCMC());
		viewForm.setSLDG(bean.getSLDG());
		viewForm.setDGLXDH(bean.getDGLXDH());
		viewForm.setGKWX(bean.getGKWX());
		viewForm.setSFTYFFWX(bean.getSFTYFFWX());
		viewForm.setVIPKH(bean.getVIPKH());
		viewForm.setGKXM(bean.getGKXM());
		viewForm.setGKLXDH(bean.getGKLXDH());
		viewForm.setSCSJ(bean.getSCSJ());
		viewForm.setJJCD(bean.getJJCD());
		viewForm.setKH(bean.getKH());
		viewForm.setTHRQ(bean.getTHRQ());
		viewForm.setWTMS(bean.getWTMS());
		viewForm.setYSGS(bean.getYSGS());
		viewForm.setYDH(bean.getYDH());
		viewForm.setFHDZ(bean.getFHDZ());
		viewForm.setSHDZ(bean.getSHDZ());
		viewForm.setSHR(bean.getSHR());
		viewForm.setSHRLXDH(bean.getSHRLXDH());
		viewForm.setBZXX(bean.getBZXX());
		viewForm.setWXXZ1(bean.getWXXZ1());
		viewForm.setWTD1(bean.getWTD1());
		viewForm.setQY1(bean.getQY1());
		viewForm.setXXD1(bean.getXXD1());
		viewForm.setWXXZ2(bean.getWXXZ2());
		viewForm.setWTD2(bean.getWTD2());
		viewForm.setQY2(bean.getQY2());
		viewForm.setXXD2(bean.getXXD2());
		viewForm.setPDCLFS(bean.getPDCLFS());
		viewForm.setZRBM(bean.getZRBM());
		viewForm.setTHDH(bean.getTHDH());
		viewForm.setTCCLJG(bean.getTCCLJG());
		viewForm.setJCYY(bean.getJCYY());
		viewForm.setTX(bean.getTX());
		viewForm.setSFSF(bean.getSFSF());
		viewForm.setJHWXTS(bean.getJHWXTS());
		viewForm.setSFJE(bean.getSFJE());
		viewForm.setSFNR(bean.getSFNR());
		viewForm.setPJPDBZ(bean.getPJPDBZ());
		viewForm.setWXR(bean.getWXR());
		viewForm.setWXSJ(bean.getWXSJ());
		viewForm.setDjr(bean.getDjr());
		viewForm.setDjsj(bean.getDjsj());
		viewForm.setPJPDR(bean.getPJPDR());
		viewForm.setPJPDSJ(bean.getPJPDSJ());
		viewForm.setTTSPR(bean.getTTSPR());
		viewForm.setTTSPSJ(bean.getTTSPSJ());
		viewForm.setWXQRR(bean.getWXQRR());
		viewForm.setWXQRSJ(bean.getWXQRSJ());
		viewForm.setZT(bean.getZT());
		
		if(viewForm.getJJCD()!=null && !viewForm.getJJCD().equals("")&&viewForm.getJJCD().equals("01")){
			viewForm.setJJCD("很急");
		}
		if(viewForm.getJJCD()!=null && !viewForm.getJJCD().equals("")&&viewForm.getJJCD().equals("02")){
			viewForm.setJJCD("急");
		}
		if(viewForm.getJJCD()!=null && !viewForm.getJJCD().equals("")&&viewForm.getJJCD().equals("03")){
			viewForm.setJJCD("一般");
		}
		
		request.setAttribute("repairImageRecordList",service.getImageInfo(viewForm.getGuid(), "待修图片"));
		request.setAttribute("checkImageRecordList", service.getImageInfo(viewForm.getGuid(), "待检图片"));
		
		return mapping.findForward("viewMaintenanceInfo");
	} 
	
}