package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>市场活动审批</title>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/common.css\" type=\"text/css\"></link>\r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"./dataTables/css/jquery.dataTables.css\" type=\"text/css\"></link>\r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"./jquery-ui/jquery.ui.all.css\" type=\"text/css\"></link>\r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("  \t\tvar oTable,pTable;\r\n");
      out.write("  \t\tvar xmlHttp1,xmlHttp2,xmlHttp3,xmlHttp4,xmlHttp5,xmlHttp6,xmlHttp7,xmlHttp8,xmlHttp9,xmlHttp10;\r\n");
      out.write("  \t\tvar id,type,detail,depot,supervisor,begin,end;\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t$(document).ready(function(){\r\n");
      out.write("  \t\t\toTable = $(\"#listData\").dataTable({\r\n");
      out.write("\t\t\t\t\"bFilter\": false,\r\n");
      out.write("\t\t\t\t\"bSort\": true,\r\n");
      out.write("\t\t\t\t\"bAutoWidth\": true,\r\n");
      out.write("\t\t\t\t\"bLengthChange\": false,\r\n");
      out.write("\t\t\t\t\"bInfo\": false,\r\n");
      out.write("\t\t\t\t\"bProcessing\": true,\r\n");
      out.write("\t\t\t\t\"bScrollInfinite\": true,\r\n");
      out.write("\t\t\t\t\"sScrollY\": \"320px\",\r\n");
      out.write("\t\t        \"sScrollX\": \"1800px\",\r\n");
      out.write("\t\t        \"oLanguage\": {\r\n");
      out.write("\t\t\t      \"sEmptyTable\": \"没有记录\"\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tpTable = $(\"#productData\").dataTable({\r\n");
      out.write("\t\t\t\t\"bFilter\": false,\r\n");
      out.write("\t\t\t\t\"bSort\": true,\r\n");
      out.write("\t\t\t\t\"bAutoWidth\": true,\r\n");
      out.write("\t\t\t\t\"bLengthChange\": false,\r\n");
      out.write("\t\t\t\t\"bInfo\": false,\r\n");
      out.write("\t\t\t\t\"bProcessing\": true,\r\n");
      out.write("\t\t\t\t\"bScrollInfinite\": true,\r\n");
      out.write("\t\t\t\t\"sScrollY\": \"220px\",\r\n");
      out.write("\t\t        \"sScrollX\": \"840px\",\r\n");
      out.write("\t\t        \"oLanguage\": {\r\n");
      out.write("\t\t\t      \"sEmptyTable\": \"没有记录\"\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#s_button\").button();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#dialog\").dialog({\r\n");
      out.write("\t\t\t\tautoOpen: false,\r\n");
      out.write("\t\t\t\tresizable: false,\r\n");
      out.write("\t\t\t\twidth:350,\r\n");
      out.write("\t\t\t\theight:180,\r\n");
      out.write("\t\t\t\tmodal: true,\r\n");
      out.write("\t\t\t\tbuttons: {\r\n");
      out.write("\t\t\t\t\t\"提交\": function() {\r\n");
      out.write("\t\t\t\t\t\tvar cmpg_id = \"\";\r\n");
      out.write("\t\t\t\t\t\tvar num = 0;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif ($(\"#dialog input:checked\").length==0)\r\n");
      out.write("\t\t\t\t\t\t\talert(\"请选择审批状态\");\r\n");
      out.write("\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\tnum = $(\"#listData input:checked:visible\").length;\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#listData input:checked:visible\").each(function(i){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).parent().parent().hide();\r\n");
      out.write("\t\t\t\t\t\t\t\tif (i != num-1)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcmpg_id = cmpg_id + $(this).parent().parent().find(\".a_id\").text() + \",\";\r\n");
      out.write("\t\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcmpg_id = cmpg_id + $(this).parent().parent().find(\".a_id\").text();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tdoCheck(cmpg_id,$(\"#dialog input:checked\").val());\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("  \t\t\tgetManage();\r\n");
      out.write("  \t\t\tgetYear();\r\n");
      out.write("  \t\t\tgetType();\r\n");
      out.write("  \t\t\t//getFlag();\r\n");
      out.write("  \t\t\tif ($(\"#search div select#s_flag\").val() == 1) {\r\n");
      out.write("\t\t\t\tgetStage();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("  \t\t\tgetList(\"\",\"\",\"\",\"\",1,\"\",\"\",\"\",\"\");\r\n");
      out.write("  \t\t\t\r\n");
      out.write("\t\t\t$(\"#s_begin\").datepicker();\r\n");
      out.write("\t\t\t$(\"#s_end\").datepicker();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#search div #s_depot\").autocomplete({\r\n");
      out.write("\t\t\t    source: function(request, response) {\r\n");
      out.write("\t\t\t        $.ajax({\r\n");
      out.write("\t\t\t            url: \"AjaxServlet\",\r\n");
      out.write("\t\t\t            dataType: \"json\",\r\n");
      out.write("\t\t\t            data: {\r\n");
      out.write("\t\t\t                action: \"getDepot\",\r\n");
      out.write("\t\t\t                dept: $(\"#search div #s_depot\").val()\r\n");
      out.write("\t\t\t            },\r\n");
      out.write("\t\t\t            success: function(data) {\r\n");
      out.write("\t\t\t            \tresponse( $.map( data.Depot, function( item ) {\r\n");
      out.write("\t\t\t\t\t\t\t\treturn {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlabel: item.Value,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue: item.Value\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}));\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\t\t\t\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction createXMLHttpRequest() {\r\n");
      out.write("\t\t\tif (window.ActiveXObject) {\r\n");
      out.write("\t\t\t\txmlHttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t} else if (window.XMLHttpRequest) {\r\n");
      out.write("\t\t\t\txmlHttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn xmlHttp;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getManage() {\t\t\t\r\n");
      out.write("\t\t\txmlHttp1 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp1.onreadystatechange = getManageProcessor;\r\n");
      out.write("\t\t\txmlHttp1.open(\"GET\",\"AjaxServlet?action=getManage&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp1.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getManageProcessor() {\r\n");
      out.write("\t\t\tif (xmlHttp1.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp1.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp1.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (obj['1'] == null)\r\n");
      out.write("\t\t\t\t\t\t$(\"#manageType .m_type#1\").text(\"待审批的活动(0)\");\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t$(\"#manageType .m_type#1\").text(\"待审批的活动(\"+obj['1']+\")\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (obj['2'] == null && obj['4'] == null)\r\n");
      out.write("\t\t\t\t\t\t$(\"#manageType .m_type#4\").text(\"已审批的活动(0)\");\r\n");
      out.write("\t\t\t\t\telse if (obj['2'] == null)\r\n");
      out.write("\t\t\t\t\t\t$(\"#manageType .m_type#4\").text(\"已审批的活动(\"+(obj['4'])+\")\");\r\n");
      out.write("\t\t\t\t\telse if (obj['4'] == null)\r\n");
      out.write("\t\t\t\t\t\t$(\"#manageType .m_type#4\").text(\"已审批的活动(\"+(obj['2'])+\")\");\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t$(\"#manageType .m_type#4\").text(\"已审批的活动(\"+(obj['2']+obj['4'])+\")\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (obj['0'] == null)\r\n");
      out.write("\t\t\t\t\t\t$(\"#manageType .m_type#0\").text(\"未提交的活动(0)\");\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t$(\"#manageType .m_type#0\").text(\"未提交的活动(\"+obj['0']+\")\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getList(year,type,detail,stage,flag,subFlag,begin,name,depot,end) {\t\t\t\r\n");
      out.write("\t\t\txmlHttp2 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp2.onreadystatechange = getListProcessor;\r\n");
      out.write("\t\t\txmlHttp2.open(\"GET\",\"AjaxServlet?action=getList&year=\"+year+\"&type=\"+type+\"&detail=\"+detail+\"&stage=\"+stage+\"&flag=\"+flag+\"&subFlag=\"+subFlag+\"&begin=\"+begin+\"&end=\"+end+\"&name=\"+name+\"&depot=\"+depot+\"&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp2.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getListProcessor() {\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tif (xmlHttp2.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp2.status == 200) {\r\n");
      out.write("\t\t\t\t\toTable.fnDestroy();\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp2.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor (var i = 0;i < obj.List.length;i++) {\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<tr>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='sel'>\";\r\n");
      out.write("\t\t\t\t\t\tif (obj.List[i].ISPASSED == \"null\" || obj.List[i].ISPASSED == \"\")\r\n");
      out.write("\t\t\t\t\t\t\thtml = html + \"<input type='checkbox'>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='a_name'>\"+obj.List[i].CMPGNAME+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='dq'>\"+obj.List[i].DQ+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='d_name'>\"+obj.List[i].DEPOT+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='m_supervisor'>\"+obj.List[i].DD+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='a_type'>\"+obj.List[i].TYPE+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='a_detail'>\"+obj.List[i].DETAIL+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='begin'>\"+obj.List[i].START+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='end'>\"+obj.List[i].END+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='a_scheme'>\"+obj.List[i].NAME+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='min_goal'>\"+obj.List[i].MIN+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='max_goal'>\"+obj.List[i].MAX+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='cost'>\"+obj.List[i].COST+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='return'>\"+obj.List[i].RETURN+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='isPassed'>\"+obj.List[i].ISPASSED+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='a_id'>\"+obj.List[i].ID+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"</tr>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#listData tbody\").html(html);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#list tbody tr\").dblclick(function(){\r\n");
      out.write("\t\t\t\t\t\ttype = $(this).find(\".a_type\").text();\r\n");
      out.write("\t\t\t\t\t\tdetail = $(this).find(\".a_detail\").text();\r\n");
      out.write("\t\t\t\t\t\tdepot = $(this).find(\".d_name\").text();\r\n");
      out.write("\t\t\t\t\t\tsupervisor = $(this).find(\".m_supervisor\").text();\r\n");
      out.write("\t\t\t\t\t\tbegin = $(this).find(\".begin\").text();\r\n");
      out.write("\t\t\t\t\t\tend = $(this).find(\".end\").text();\r\n");
      out.write("\t\t\t\t\t\tgetListDetail($(this).find(\".a_id\").text());\r\n");
      out.write("\t\t\t\t\t\tgetProduct($(this).find(\".a_id\").text());\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#list thead .sel\").click(function(){\r\n");
      out.write("\t\t\t\t\t\tif ($(\"#list tbody .sel input\").not(\":checked\").length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#list tbody .sel input\").attr(\"checked\",false);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#list tbody .sel input\").attr(\"checked\",true);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\toTable = $(\"#listData\").dataTable({\r\n");
      out.write("\t\t\t\t\t\t\"bFilter\": false,\r\n");
      out.write("\t\t\t\t\t\t\"bSort\": true,\r\n");
      out.write("\t\t\t\t\t\t\"bAutoWidth\": true,\r\n");
      out.write("\t\t\t\t\t\t\"bLengthChange\": false,\r\n");
      out.write("\t\t\t\t\t\t\"bInfo\": false,\r\n");
      out.write("\t\t\t\t\t\t\"bProcessing\": true,\r\n");
      out.write("\t\t\t\t\t\t\"bPaginate\": false,\r\n");
      out.write("\t\t\t\t\t\t\"bScrollInfinite\": true,\r\n");
      out.write("\t\t\t\t\t\t\"sScrollY\": \"320px\",\r\n");
      out.write("\t\t\t\t        \"sScrollX\": \"1800px\",\r\n");
      out.write("\t\t\t\t        \"oLanguage\": {\r\n");
      out.write("\t\t\t\t\t      \"sEmptyTable\": \"没有记录\"\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$(\"#progress\").hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getYear() {\t\t\r\n");
      out.write("\t\t\txmlHttp3 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp3.onreadystatechange = getYearProcessor;\r\n");
      out.write("\t\t\txmlHttp3.open(\"GET\",\"AjaxServlet?action=getYear&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp3.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getYearProcessor() {\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tif (xmlHttp3.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp3.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp3.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor (var i = 0;i < obj.Year.length;i++) {\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<option value='\"+obj.Year[i].Key+\"'>\"+obj.Year[i].Value+\"</option>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#search div select#s_year\").html(html);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getType() {\t\t\r\n");
      out.write("\t\t\txmlHttp4 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp4.onreadystatechange = getTypeProcessor;\r\n");
      out.write("\t\t\txmlHttp4.open(\"GET\",\"AjaxServlet?action=getType&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp4.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getTypeProcessor() {\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tif (xmlHttp4.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp4.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp4.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor (var i = 0;i < obj.Type.length;i++) {\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<option value='\"+obj.Type[i].Key+\"'>\"+obj.Type[i].Value+\"</option>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#search div select#s_type\").html(html);\r\n");
      out.write("\t\t\t\t\tgetDetail();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getDetail() {\t\t\r\n");
      out.write("\t\t\txmlHttp5 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp5.onreadystatechange = getDetailProcessor;\r\n");
      out.write("\t\t\txmlHttp5.open(\"GET\",\"AjaxServlet?action=getDetail&type=\"+$(\"#search div select#s_type\").val()+\"&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp5.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getDetailProcessor() {\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tif (xmlHttp5.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp5.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp5.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor (var i = 0;i < obj.Detail.length;i++) {\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<option value='\"+obj.Detail[i].Key+\"'>\"+obj.Detail[i].Value+\"</option>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#search div select#s_detail\").html(html);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getStage() {\t\t\r\n");
      out.write("\t\t\txmlHttp6 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp6.onreadystatechange = getStageProcessor;\r\n");
      out.write("\t\t\txmlHttp6.open(\"GET\",\"AjaxServlet?action=getStage&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp6.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getStageProcessor() {\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tif (xmlHttp6.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp6.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp6.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor (var i = 0;i < obj.Stage.length;i++) {\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<option value='\"+obj.Stage[i].Key+\"'>\"+obj.Stage[i].Value+\"</option>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#search div select#s_stage\").html(html);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getFlag() {\t\t\r\n");
      out.write("\t\t\txmlHttp7 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp7.onreadystatechange = getFlagProcessor;\r\n");
      out.write("\t\t\txmlHttp7.open(\"GET\",\"AjaxServlet?action=getFlag&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp7.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getFlagProcessor() {\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tif (xmlHttp7.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp7.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp7.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor (var i = 0;i < obj.Flag.length;i++) {\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<option value='\"+obj.Flag[i].Key+\"'>\"+obj.Flag[i].Value+\"</option>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#search div select#s_flag\").html(html);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getListDetail(id) {\t\t\r\n");
      out.write("\t\t\txmlHttp8 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp8.onreadystatechange = getListDetailProcessor;\r\n");
      out.write("\t\t\txmlHttp8.open(\"GET\",\"AjaxServlet?action=getListDetail&id=\"+id+\"&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp8.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getListDetailProcessor() {\r\n");
      out.write("\t\t\tif (xmlHttp8.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp8.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp8.responseText+')');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_year\").text(\"年份：\"+obj.YEAR);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_type\").text(\"活动类型：\"+type);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_detail\").text(\"活动明细：\"+detail);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_depot\").text(\"店铺：\"+depot);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_supervisor\").text(\"督导：\"+supervisor);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_tel\").text(\"电话：\"+obj.TEL);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_begin\").text(\"开始时间：\"+begin);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_end\").text(\"结束时间：\"+end);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpBegin\").text(\"开始范围：\"+obj.HPBEGIN);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpEnd\").text(\"结束范围：\"+obj.HPEND);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpLevel\").text(\"款式等级：\"+obj.HPLEVEL);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpBrand\").text(\"品牌：\"+obj.HPBRAND);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpType\").text(\"品类：\"+obj.HPTYPE);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpYear\").text(\"年份：\"+obj.HPYEAR);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpSeason\").text(\"季节：\"+obj.HPSEASON);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpDate\").text(\"波段：\"+obj.HPDATE);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpType1\").text(\"促销类型：\"+obj.HPTYPE1);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpWay\").text(\"优惠方式：\"+obj.HPWAY);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpPrice\").text(\"优惠折扣/金额：\"+obj.HPPRICE);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_hpUse\").text(\"使用方式：\"+obj.HPUSE);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_giveNum\").text(\"赠送品类数量：\"+obj.GIVENUM);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_isCustom\").text(\"是否制定促销款式：\"+obj.ISCUSTOM);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_isVip\").text(\"是否只允许VIP：\"+obj.ISVIP);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_isDiscount\").text(\"是否VIP折上折：\"+obj.ISDISCOUNT);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_comment\").text(\"备注：\"+obj.COMMENT);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_maxGoal\").text(\"攀登目标：\"+obj.MAXGOAL);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_minGoal\").text(\"必保目标：\"+obj.MINGOAL);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_pos\").text(\"销售录入POS：\"+obj.POS);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_cost\").text(\"活动费用预算：\"+obj.COST);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_gift\").text(\"礼品支持：\"+obj.GIFT);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_return\").text(\"合同回款：\"+obj.RETURN);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_finish\").text(\"实际完成：\"+obj.FINISH);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_avgPrice\").text(\"平均客单价：\"+obj.AVGPRICE);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_avgNum\").text(\"平均客单件：\"+obj.AVGNUM);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_maxNum\").text(\"最高客单件：\"+obj.MAXNUM);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_vipPrice\").text(\"VIP消费金额：\"+obj.VIPPRICE);\r\n");
      out.write("\t\t\t\t\t$(\"#detail #d_vipNum\").text(\"VIP消费人数：\"+obj.VIPNUM);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction doCheck(id,val) {\t\t\r\n");
      out.write("\t\t\txmlHttp9 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp9.onreadystatechange = doCheckProcessor;\r\n");
      out.write("\t\t\txmlHttp9.open(\"GET\",\"AjaxServlet?action=doCheck&id=\"+id+\"&val=\"+val+\"&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp9.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction doCheckProcessor() {\r\n");
      out.write("\t\t\tif (xmlHttp9.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp9.status == 200) {\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp9.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (obj.error != null)\r\n");
      out.write("\t\t\t\t\t\talert(obj.error);\r\n");
      out.write("\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\tgetManage();\r\n");
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t//getList($(\"#s_year\").val(),$(\"#s_type\").val(),$(\"#s_detail\").val(),$(\"#s_stage\").val(),id,$(\"#s_flag\").val(),$(\"#s_begin\").val(),$(\"#s_name\").val(),$(\"#s_depot\").val(),$(\"#s_end\").val());\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getProduct(id) {\t\t\r\n");
      out.write("\t\t\txmlHttp10 = createXMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp10.onreadystatechange = getProductProcessor;\r\n");
      out.write("\t\t\txmlHttp10.open(\"GET\",\"AjaxServlet?action=getProduct&id=\"+id+\"&tm=\"+new Date().toString());\r\n");
      out.write("\t\t\txmlHttp10.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getProductProcessor() {\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\tif (xmlHttp10.readyState == 4) {\r\n");
      out.write("\t\t\t\tif (xmlHttp10.status == 200) {\r\n");
      out.write("\t\t\t\t\tpTable.fnDestroy();\r\n");
      out.write("\t\t\t\t\tvar obj = eval('('+xmlHttp10.responseText+')');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor (var i = 0;i < obj.List.length;i++) {\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<tr>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='pt'>\"+obj.List[i].PT+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='pt_skc'>\"+obj.List[i].PTSKC+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='pt_year'>\"+obj.List[i].PTYEAR+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='pt_season'>\"+obj.List[i].PTSEASON+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='pt_type'>\"+obj.List[i].PTTYPE+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='pt_big'>\"+obj.List[i].PTBIG+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='pt_small'>\"+obj.List[i].PTSMALL+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"<td class='pt_price'>\"+obj.List[i].PTPRICE+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtml = html + \"</tr>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#productData tbody\").html(html);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tpTable = $(\"#productData\").dataTable({\r\n");
      out.write("\t\t\t\t\t\t\"bFilter\": false,\r\n");
      out.write("\t\t\t\t\t\t\"bSort\": true,\r\n");
      out.write("\t\t\t\t\t\t\"bAutoWidth\": true,\r\n");
      out.write("\t\t\t\t\t\t\"bLengthChange\": false,\r\n");
      out.write("\t\t\t\t\t\t\"bInfo\": false,\r\n");
      out.write("\t\t\t\t\t\t\"bProcessing\": true,\r\n");
      out.write("\t\t\t\t\t\t\"bPaginate\": false,\r\n");
      out.write("\t\t\t\t\t\t\"bScrollInfinite\": true,\r\n");
      out.write("\t\t\t\t\t\t\"sScrollY\": \"220px\",\r\n");
      out.write("\t\t\t\t        \"sScrollX\": \"840px\",\r\n");
      out.write("\t\t\t\t        \"oLanguage\": {\r\n");
      out.write("\t\t\t\t\t      \"sEmptyTable\": \"没有记录\"\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("  \t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"title\">\r\n");
      out.write("    \t<div id=\"sign\">CRM Assistant</div>\r\n");
      out.write("    \t<div id=\"titleName\">市场活动</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("    \t<div id=\"manage\">\r\n");
      out.write("    \t\t<div id=\"manageTitle\">待处理活动</div>\r\n");
      out.write("    \t\t<div id=\"manageType\">\r\n");
      out.write("    \t\t\t<div id=\"1\" class=\"m_type\">待审批的活动</div>\r\n");
      out.write("    \t\t\t<div id=\"4\" class=\"m_type\">已审批的活动</div>\r\n");
      out.write("    \t\t\t<div id=\"0\" class=\"m_type\">未提交的活动</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div id=\"data\">\r\n");
      out.write("    \t\t<div id=\"search\">\r\n");
      out.write("    \t\t\t<div id=\"searchTitle\">\r\n");
      out.write("    \t\t\t\t<div id=\"check\"></div>\r\n");
      out.write("\t\t\t\t\t<div id=\"checkText\">批量审批</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"search_close\" class=\"close\"><img src=\"./image/close.png\"></img></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">活动年份:</div>\r\n");
      out.write("\t    \t\t\t\t<select class=\"left\" id=\"s_year\">\r\n");
      out.write("\t    \t\t\t\t</select>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">活动类型:</div>\r\n");
      out.write("\t    \t\t\t\t<select class=\"left\" id=\"s_type\">\r\n");
      out.write("\t    \t\t\t\t</select>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">类型明细:</div>\r\n");
      out.write("\t    \t\t\t\t<select class=\"left\" id=\"s_detail\">\r\n");
      out.write("\t    \t\t\t\t</select>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\" style=\"width: 100px;\">\r\n");
      out.write("    \t\t\t\t\t<input type=\"button\" class=\"left\" id=\"s_button\" value=\"查询\"/>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">审批状态:</div>\r\n");
      out.write("\t    \t\t\t\t<select class=\"left\" id=\"s_flag\">\r\n");
      out.write("\t    \t\t\t\t</select>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">审批阶段:</div>\r\n");
      out.write("\t    \t\t\t\t<select class=\"left\" id=\"s_stage\">\r\n");
      out.write("    \t\t\t\t\t</select>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">开始时间:</div>\r\n");
      out.write("\t    \t\t\t\t<input type=\"text\" class=\"left\" id=\"s_begin\">\r\n");
      out.write("\t    \t\t\t\t</input>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">活动名称:</div>\r\n");
      out.write("\t    \t\t\t\t<input type=\"text\" class=\"left\" id=\"s_name\">\r\n");
      out.write("\t    \t\t\t\t</input>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">店铺名称:</div>\r\n");
      out.write("\t    \t\t\t\t<input type=\"text\" class=\"left\" id=\"s_depot\">\r\n");
      out.write("\t    \t\t\t\t</input>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"condition\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"left\">结束时间:</div>\r\n");
      out.write("\t    \t\t\t\t<input type=\"text\" class=\"left\" id=\"s_end\">\r\n");
      out.write("\t    \t\t\t\t</input>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div id=\"list\">\r\n");
      out.write("    \t\t\t<table id=\"listData\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"sel\">全选</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"a_name\">活动名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"dq\">分公司</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"d_name\">店铺名</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"m_supervisor\">督导</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"a_type\">活动类型</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"a_detail\">活动明细</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"begin\">开始时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"end\">结束时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"a_scheme\">活动方案</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"min_goal\">必保目标</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"max_goal\">攀登目标</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"cost\">活动费用预算</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"return\">活动回款</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"isPassed\">是否审核通过</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"a_id\">ID</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div id=\"dialog\" title=\"审批\">\r\n");
      out.write("    \t\t\t<div id=\"checkButton\">\r\n");
      out.write("    \t\t\t\t<div class=\"checkLabel\">审批意见</div>\r\n");
      out.write("    \t\t\t\t<div class=\"checkArea\">\r\n");
      out.write("\t    \t\t\t\t<input type=\"radio\" name=\"check\" value=\"1001\"/>批准\r\n");
      out.write("\t    \t\t\t\t<input type=\"radio\" name=\"check\" value=\"1002\"/>不批准（驳回）\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div id=\"detail\">\r\n");
      out.write("    \t\t\t<div id=\"detailTitle\" style=\"margin: 0;\">\r\n");
      out.write("    \t\t\t\t活动明细\r\n");
      out.write("    \t\t\t\t<div id=\"detail_close\" class=\"close\"><img src=\"./image/close.png\"></img></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_1\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_year\" class=\"left long\">年份：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_type\" class=\"left long\">活动类型：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_detail\" class=\"left long\">活动明细：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_2\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_depot\" class=\"left long\">店铺：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_supervisor\" class=\"left short\">督导：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_tel\" class=\"left short\">电话：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_3\">活动方案</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_4\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_begin\" class=\"left long\">开始时间：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_end\" class=\"left long\">结束时间：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_5\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpType1\" class=\"left long\">促销类型：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpBegin\" class=\"left long\">开始范围：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpEnd\" class=\"left long\">结束范围：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_6\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpBrand\" class=\"left long\">品牌：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpYear\" class=\"left long\">年份：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpSeason\" class=\"left long\">季节：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_7\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpDate\" class=\"left long\">波段：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpType\" class=\"left long\">品类：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpLevel\" class=\"left long\">款式等级：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_8\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpWay\" class=\"left long\">优惠方式：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpPrice\" class=\"left long\">优惠折扣/金额：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_hpUse\" class=\"left long\">使用方式：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_9\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_giveNum\" class=\"left long\">赠送品类数量：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_10\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_isCustom\" class=\"left long\">是否制定促销款式：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_isVip\" class=\"left long\">是否只允许VIP：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_isDiscount\" class=\"left long\">是否VIP折上折：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_11\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_comment\" class=\"left\">备注：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_18\">\r\n");
      out.write("    \t\t\t\t方案明细\r\n");
      out.write("    \t\t\t\t<div id=\"pt_close\" class=\"close\"><img src=\"./image/close.png\"></img></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_19\">\r\n");
      out.write("    \t\t\t\t<table id=\"productData\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"pt\">产品</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"pt_skc\">产品编号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"pt_year\">年份</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"pt_season\">季节</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"pt_type\">种类</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"pt_big\">大类</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"pt_small\">小类</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th class=\"pt_price\">零售现价</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_12\">活动目标</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_13\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_maxGoal\" class=\"left long\">攀登目标：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_minGoal\" class=\"left long\">必保目标：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_pos\" class=\"left long\">销售录入POS：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_14\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_cost\" class=\"left long\">活动费用预算：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_gift\" class=\"left long\">礼品支持：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_return\" class=\"left long\">合同回款：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_15\">活动结果</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_16\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_finish\" class=\"left long\">实际完成：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_avgPrice\" class=\"left long\">平均客单价：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_avgNum\" class=\"left long\">平均客单件：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_maxNum\" class=\"left long\">最高客单件：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div id=\"detail_17\">\r\n");
      out.write("    \t\t\t\t<div id=\"d_vipPrice\" class=\"left long\">VIP消费金额：</div>\r\n");
      out.write("    \t\t\t\t<div id=\"d_vipNum\" class=\"left long\">VIP消费人数：</div>\r\n");
      out.write("    \t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div class=\"clear\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"progress\">\r\n");
      out.write("    \t<div id=\"background\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \t$(\"#search div select#s_type\").change(function(){\r\n");
      out.write("\t\t\tgetDetail();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//$(\"#search div select#s_flag\").change(function(){\r\n");
      out.write("\t\t//\tif ($(\"#search div select#s_flag\").val() == 1) {\r\n");
      out.write("\t\t//\t\tgetStage();\r\n");
      out.write("\t\t//\t} else {\r\n");
      out.write("\t\t//\t\t$(\"#search div select#s_stage\").html(\"\");\r\n");
      out.write("\t\t//\t}\r\n");
      out.write("\t\t//});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".m_type\").click(function(){\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t$(\"#progress\").show();\r\n");
      out.write("\t\t\tid = $(this).attr(\"id\");\r\n");
      out.write("\t\t\tgetList(\"\",\"\",\"\",\"\",id,\"\",\"\",\"\",\"\",\"\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (id == \"1\") {\r\n");
      out.write("\t\t\t\thtml = html + \"<option value='null'>未审核</option>\";\r\n");
      out.write("\t\t\t\thtml = html + \"<option value='1001'>通过</option>\";\r\n");
      out.write("\t\t\t\thtml = html + \"<option value='1002'>未通过</option>\";\r\n");
      out.write("\t\t\t\t$(\"#search div select#s_flag\").html(html);\r\n");
      out.write("\t\t\t} else if (id == \"4\") {\r\n");
      out.write("\t\t\t\thtml = html + \"<option value='1001'>通过</option>\";\r\n");
      out.write("\t\t\t\thtml = html + \"<option value='1002'>未通过</option>\";\r\n");
      out.write("\t\t\t\t$(\"#search div select#s_flag\").html(html);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#s_button\").click(function(){\r\n");
      out.write("\t\t\t$(\"#progress\").show();\r\n");
      out.write("\r\n");
      out.write("\t\t\tgetList($(\"#s_year\").val(),$(\"#s_type\").val(),$(\"#s_detail\").val(),$(\"#s_stage\").val(),id,$(\"#s_flag\").val(),$(\"#s_begin\").val(),$(\"#s_name\").val(),$(\"#s_depot\").val(),$(\"#s_end\").val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#check\").click(function() {\r\n");
      out.write("\t\t\t$(\"#dialog\").dialog(\"open\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#search_close\").click(function(){\r\n");
      out.write("\t\t\tif ($(this).attr(\"class\")==\"close\") {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"close\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"open\");\r\n");
      out.write("\t\t\t\t$(this).find(\"img\").attr(\"src\",\"./image/open.png\");\r\n");
      out.write("\t\t\t\t$(\".condition\").parent().hide();\r\n");
      out.write("\t\t\t\t$(\"#manage\").height($(\"#data\").height());\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"open\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"close\");\r\n");
      out.write("\t\t\t\t$(this).find(\"img\").attr(\"src\",\"./image/close.png\");\r\n");
      out.write("\t\t\t\t$(\".condition\").parent().show();\r\n");
      out.write("\t\t\t\t$(\"#manage\").height($(\"#data\").height());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#detail_close\").click(function(){\r\n");
      out.write("\t\t\tif ($(this).attr(\"class\")==\"close\") {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"close\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"open\");\r\n");
      out.write("\t\t\t\t$(this).find(\"img\").attr(\"src\",\"./image/open.png\");\r\n");
      out.write("\t\t\t\t$(this).parent().parent().find(\"div\").not(\"#detailTitle\").hide();\r\n");
      out.write("\t\t\t\t$(\"#detailTitle div\").show();\r\n");
      out.write("\t\t\t\t$(\"#manage\").height($(\"#data\").height());\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"open\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"close\");\r\n");
      out.write("\t\t\t\t$(this).find(\"img\").attr(\"src\",\"./image/close.png\");\r\n");
      out.write("\t\t\t\t$(this).parent().parent().find(\"div\").show();\r\n");
      out.write("\t\t\t\t$(\"#manage\").height($(\"#data\").height());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#pt_close\").click(function(){\r\n");
      out.write("\t\t\tif ($(this).attr(\"class\")==\"close\") {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"close\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"open\");\r\n");
      out.write("\t\t\t\t$(this).find(\"img\").attr(\"src\",\"./image/open.png\");\r\n");
      out.write("\t\t\t\t$(\"#detail_19\").hide();\r\n");
      out.write("\t\t\t\t$(\"#manage\").height($(\"#data\").height());\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"open\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"close\");\r\n");
      out.write("\t\t\t\t$(this).find(\"img\").attr(\"src\",\"./image/close.png\");\r\n");
      out.write("\t\t\t\t$(\"#detail_19\").show();\r\n");
      out.write("\t\t\t\t$(\"#manage\").height($(\"#data\").height());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
