package org.apache.jsp.expense;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ep.org.util.NumberUtil;
import java.util.*;
import ep.org.branch.expense.dojo.UserInfo;
import ep.org.branch.expense.constant.ExpenseConstant;
import ep.org.branch.expense.dojo.SelectOptionObj;
import ep.org.branch.expense.dojo.PaymentInfo;
import ep.org.branch.expense.dojo.PaymentPurposeCost;

public final class paymentApplyPrint_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>付款申请</title>\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( path);
      out.write("/css/mycommon.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print( path);
      out.write("/myjs/myTime.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"");
      out.print( path);
      out.write("/js/jquery-1.5.2.min.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function Print() {  \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\t\tif (document.all.eprint.defaultPrinterName.length==0){\r\n");
      out.write("\t\t\talert(\"请先安装打印机，再执行此功能！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  \t    eprint.InitPrint();\r\n");
      out.write("  \t    eprint.marginTop=1;\r\n");
      out.write("  \t\teprint.marginLeft=10;\r\n");
      out.write(" \t\teprint.marginRight=10;\r\n");
      out.write("  \t\teprint.marginBottom=1;\r\n");
      out.write("  \t\teprint.header = \"\";\r\n");
      out.write("  \t\teprint.footer = \"\";\r\n");
      out.write("  \t\teprint.Print();\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t//document.all.eprint.Print(true);//不弹出打印对话框直接打印\r\n");
      out.write("\t}catch(e){\r\n");
      out.write("\t\tinitForm();\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function initForm(){\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\tif (document.all.eprint.defaultPrinterName.length==0){\r\n");
      out.write("\t\talert(\"请先安装打印机，再执行此功能！\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tcatch(e){\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar url=document.getElementById(\"webContext\").value+'/expense/webprintDownload.jsp';\r\n");
      out.write("\t\twindow.open(url,'webprint打印控件下载','scrollbars=yes,width=400px,height=200px,resizable=yes,menubar=no,status=no,location=no');\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" </script>\r\n");
      out.write("\t<body  onload=\"Print()\">\r\n");
      out.write("\t\t <input type=\"hidden\" id=\"webContext\" value=\"");
      out.print(request.getContextPath() );
      out.write("\">\r\n");
      out.write("\t\t<object id=\"eprint\" classid=\"clsid:CA03A5A8-9890-49BE-BA4A-8C524EB06441\"  viewasext> </object>\r\n");
      out.write("   \t\t");
PaymentInfo paymentInfo = (PaymentInfo)request.getAttribute("expenseInfo");
      out.write("\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t\r\n");
      out.write("   <div style=\"position:relative;width: 95%;height: 100%; left: 30 \">\r\n");
      out.write("   <div align=\"center\" style=\"height: 20\"><img alt=\"\" src=\"");
      out.print(path );
      out.write("/img/image2.png\"></div>\r\n");
      out.write("    \r\n");
      out.write("    <div style=\"position:absolute;top: 50;z-index: 1\">\r\n");
      out.write("    <div align=\"center\" style=\"height: 50\">\r\n");
      out.write("    \t\r\n");
      out.write("    <font style=\"font-weight: 600;font-size: 18\">Payment Application Form</font> <br> <font  style=\"font-weight: 600;font-size: 18\">付款申请表 </font>  </div>\r\n");
      out.write("    \r\n");
      out.write("    <div align=\"right\" style=\"position: absolute;top: 2;right: 0%\">\r\n");
      out.write("   \t <img alt=\"\" src=\"");
      out.print(path);
      out.write("/barcode.bracodeServlet?image=1&type=21&data=");
      out.print(paymentInfo.getExpenseNo() );
      out.write("&height=50\" >\r\n");
      out.write("  \t</div>\r\n");
      out.write("    \t<br />\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("    <table width=\"100%\" cellPadding=0 cellSpacing=0  frame=box style=\"BORDER-COLLAPSE: collapse;\" bgColor=white borderColor=black>\t\t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td height=\"40\" class=\"td_field_thin\" width=\"25%\" align=\"center\">  Requested By/申请人<br />\r\n");
      out.write("    \t\t\t");
      out.print(paymentInfo.getEmployeeName() );
      out.write("\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" width=\"25%\" align=\"center\">Department/部门全称<br />\r\n");
      out.write("    \t\t\t");
      out.print(paymentInfo.getBranchName() );
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t </td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" width=\"25%\" align=\"center\">Cost Center.No/部门成本中心代码<br />\r\n");
      out.write("    \t\t\t");
      out.print(paymentInfo.getBranchCostCenter() );
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" width=\"25%\" align=\"center\">Date/日期\t<br />\r\n");
      out.write("    \t\t\t");
      out.print(paymentInfo.getApplyDate() );
      out.write("\t\t\t\t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td height=\"40\"  class=\"td_field_thin\" colspan=\"2\">Pay to/收款人全称：<br />\r\n");
      out.write("    \t\t\t");
      out.print(paymentInfo.getBankAccoutName() );
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" colspan=\"2\">City/Probince/省/市：<br />\r\n");
      out.write("    \t\t\t");
      out.print(paymentInfo.getProvince_city() );
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td height=\"40\"  class=\"td_field_thin\" colspan=\"2\">Bank Account/开户银行：<br />\r\n");
      out.write("    \t\t\t");
      out.print(paymentInfo.getBankName() );
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" colspan=\"2\">Bank Code/银行帐号：<br />\r\n");
      out.write("    \t\t\t");
      out.print(paymentInfo.getBankAccout() );
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td height=\"40\"  colspan=\"2\" class=\"td_field_thin\" >  Bank Instruction/其它要求说明：<br />\r\n");
      out.write("    \t\t");
      out.print(paymentInfo.getRemark() );
      out.write("\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<td colspan=\"2\" class=\"td_field_thin\" >Vendor No./供应商号:<br />\r\n");
      out.write("    \t\t");
      out.print(paymentInfo.getVendorNo() );
      out.write("\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("   \t<font style=\"font-size: 11;font-weight: 500;\">\tPayment Type/付款方式</font>\r\n");
      out.write("     \r\n");
      out.write("     <table width=\"100%\" cellPadding=0 cellSpacing=0  frame=box style=\"BORDER-COLLAPSE:collapse; \" bgColor=white borderColor=black>\t\t\r\n");
      out.write("    \t<tr valign=\"top\">\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\" width=\"14.28%\"><input type=\"checkbox\">电汇/<br/> TT</td>  \r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\" width=\"14.28%\"><input type=\"checkbox\">汇票 /<br/>Draft</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\" width=\"14.28%\"><input type=\"checkbox\">承兑汇票/<br/>Acceptance<br/> Bill\t</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\" width=\"14.28%\"><input type=\"checkbox\">转帐支票/<br/>Transfer<br/>Cheque\t</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\" width=\"14.28%\"><input type=\"checkbox\">现金/<br/>    Cash</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\" width=\"14.28%\"><input type=\"checkbox\">信用证/<br/>    Letter of <br/>     Credit\t</td>\r\n");
      out.write("    \t\t<td align=\"left\" class=\"td_field_thin\" width=\"14.28%\" >货币Cureency<br/>\r\n");
      out.write("    \t\t<input type=\"checkbox\"> 人民币 <br/><input type=\"checkbox\">美元<input type=\"checkbox\">\t欧元</td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr height=\"25\">\r\n");
      out.write("    \t\t<td colspan=\"3\" align=\"center\" class=\"td_field_thin\">Description/付款明细说明</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\">Invoice Code<br/>发票号\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\">Cost Center<br/>成本中心\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\">Acctode<br/>会计科目</td>\r\n");
      out.write("    \t\t<td align=\"center\" class=\"td_field_thin\">Amount<br/>金额</td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t");
 PaymentPurposeCost paymentPurposeCost = null;
    	   List purposeCostList = (List)request.getAttribute("purposeCostList"); 
    	   int listSize = purposeCostList.size();
    	   for(int i=0;i<listSize;i++){
    	  	 paymentPurposeCost = (PaymentPurposeCost)purposeCostList.get(i);
    		 
    	
      out.write("\r\n");
      out.write("    \t<tr height=\"20\">\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" colspan=\"3\" >");
      out.print(paymentPurposeCost.getExpensePurpose());
      out.write(" </td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\">");
      out.print(paymentPurposeCost.getInvoiceCode());
      out.write("</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\">");
      out.print(paymentPurposeCost.getCostCenterCode());
      out.print(paymentPurposeCost.getCostCenterName());
      out.write("</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" align=\"right\">");
      out.print(NumberUtil.formatFloatDecimal(2,(String)(paymentPurposeCost.getExpenseAmout().equals("")?"":paymentPurposeCost.getExpenseAmout().substring(0,paymentPurposeCost.getExpenseAmout().length()-2))));
      out.write("</td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t");
 }
    	
    	 
    	
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr  height=\"25\">\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" colspan=\"3\">  Supporting Documents/附件_____张 </td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" colspan=\"2\">       Total/合计金额：</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" colspan=\"2\"> ");
      out.print(paymentInfo.getTotalMoney() );
      out.write("  </td>\r\n");
      out.write("    \t</tr>\t\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \t<tr  height=\"25\">\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<td class=\"td_field_thin\"  colspan=\"2\">TOTAL In Words/大写总金额：</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\"  colspan=\"5\">");
      out.print(request.getAttribute("totalMoneyCN") );
      out.write(" </td>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr  height=\"30\">\r\n");
      out.write("    \t\t<td colspan=\"2\" class=\"td_field_thin\">  P.O./Contract No.定单号/合同号：<br />\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td colspan=\"3\" class=\"td_field_thin\">  GRN # / 收货单：<br />\t\t\t\t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td colspan=\"2\" class=\"td_field_thin\">  Others/其它：<br />\t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\t<tr height=\"30\">\r\n");
      out.write("    \t\t<td colspan=\"3\" class=\"td_field_thin\">    Urgent Payment/紧急付款：<br />\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t<td colspan=\"4\" class=\"td_field_thin\">   Reason/理由：<br />\t\t\t\t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td  colspan=\"7\" class=\"td_field_thin\">\r\n");
      out.write("    \t\t\t  <table border=\"0\" width=\"100%\">\r\n");
      out.write("    \t\t\t  \t<tr>\r\n");
      out.write("    \t\t\t  \t\t<td align=\"left\" class=\"td_field_thin\" colspan=\"2\">\r\n");
      out.write("    \t\t\t  \t\t\tPayment type/付款类型：\r\n");
      out.write("    \t\t\t  \t\t</td>\r\n");
      out.write("    \t\t\t  \t\t\r\n");
      out.write("    \t\t\t  \t\t<td >\r\n");
      out.write("    \t\t\t  \t\t</td>\r\n");
      out.write("    \t\t\t  \t\t<td align=\"left\" class=\"td_field_thin\">\r\n");
      out.write("    \t\t\t  \t\t\t<input type=\"checkbox\">  Equipment Payment/设备款\r\n");
      out.write("    \t\t\t  \t\t</td>\r\n");
      out.write("    \t\t\t  \t</tr>\r\n");
      out.write("    \t\t\t  \t<tr>\r\n");
      out.write("    \t\t\t  \t\t<td width=\"15%\"></td>\r\n");
      out.write("    \t\t\t  \t\t<td width=\"35%\" align=\"left\"  class=\"td_field_thin\"><input type=\"checkbox\"> Material Payment/材料费</td>\r\n");
      out.write("    \t\t\t  \t\t<td width=\"10%\"></td>\r\n");
      out.write("    \t\t\t  \t\t<td width=\"40%\" align=\"left\" class=\"td_field_thin\"><input type=\"checkbox\"> PrePayment/预付款</td>\r\n");
      out.write("    \t\t\t  \t</tr>\r\n");
      out.write("    \t\t\t  \t<tr>\r\n");
      out.write("    \t\t\t  \t\t<td ></td>\r\n");
      out.write("    \t\t\t  \t\t<td align=\"left\" class=\"td_field_thin\"><input type=\"checkbox\"> Project Payment/工程费  </td>\r\n");
      out.write("    \t\t\t  \t\t<td></td>\r\n");
      out.write("    \t\t\t  \t\t<td align=\"left\" class=\"td_field_thin\"><input type=\"checkbox\"> Other Payment/其他付款</td>\r\n");
      out.write("    \t\t\t  \t</tr>\r\n");
      out.write("    \t\t\t  \t\r\n");
      out.write("    \t\t\t  </table>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\" align=\"center\"> 复核     <br />  Checked by\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\" align=\"center\">分公司财务审核 <br />    Approved by FIN </td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\" align=\"center\">部门经理(总监)批准<br />  Approved by DM\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\" align=\"center\"> 财务经理      <br /> Approved by FM\t\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\" align=\"center\">品牌总经理      <br />Approved by BMD</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\" align=\"center\">总经理       <br />    Approved by MD</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\" align=\"center\">签 收                 <br />     Received by</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" width=\"14.28%\"></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:\t</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" >日期/Date:</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td class=\"td_field_thin\" height=\"30\" colspan=\"8\">\r\n");
      out.write("    \t\t\t\tInstruction:  <br/>1.The applicants take charge of the application's conte\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <br />\r\n");
      out.write("    <div style=\"position: absolute;top: 1000;z-index:2;left: 28%\" >\r\n");
      out.write("    \t<img alt=\"\" src=\"");
      out.print(path );
      out.write("/img/image1.jpeg\" height=\"9\">\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
