USE [epapp]
GO

/****** Object:  Table [dbo].[CM_LOGINLOG]    Script Date: 12/15/2012 16:37:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CM_LOGINLOG](
	[guid] [int] IDENTITY(1000000001,1) NOT NULL,
	[userid] [nvarchar](50) NOT NULL,
	[com] [nvarchar](50) NULL,
 CONSTRAINT [PK_CM_LOGINLOG] PRIMARY KEY CLUSTERED 
(
	[guid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


