<%@ page language="C#" masterpagefile="~/cashcard/main/car/user/carmaster.master" autoeventwireup="true" inherits="car_user_modifypsw, App_Web_modifypsw.aspx.d716d88e" title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ctplhder" Runat="Server">
    <asp:UpdatePanel id="UpdatePanel1" runat="server">
        <contenttemplate>
<TABLE height=7 cellSpacing=0 cellPadding=0 width=492 align=center border=0 ;><TR><TD style="HEIGHT: 41px" colSpan=3>&nbsp;<SPAN style="FONT-SIZE: 14pt; COLOR: #ff0000">购物卡密码修改</SPAN></TD></TR><TR><TD style="WIDTH: 86px; HEIGHT: 26px; TEXT-ALIGN: left">&nbsp;旧密码：</TD><TD style="HEIGHT: 26px">&nbsp;<asp:TextBox id="txtoldpsw" runat="server" TextMode="Password"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator2" runat="server" ControlToValidate="txtoldpsw" ErrorMessage="卡号不能为空">*</asp:RequiredFieldValidator></TD></TR><TR style="COLOR: #000000"><TD style="WIDTH: 86px; HEIGHT: 26px; TEXT-ALIGN: left">&nbsp;新密码：</TD><TD style="HEIGHT: 26px">&nbsp;<asp:TextBox id="txtnewpsw" runat="server" TextMode="Password"></asp:TextBox><asp:RequiredFieldValidator id="RFVpsw" runat="server" ControlToValidate="txtnewpsw" ErrorMessage="请输入新密码" SetFocusOnError="True">*</asp:RequiredFieldValidator></TD></TR><TR style="COLOR: #000000"><TD style="WIDTH: 86px; TEXT-ALIGN: left">确认密码：</TD><TD>&nbsp;<asp:TextBox id="txtnewpsw2" runat="server" TextMode="Password"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator3" runat="server" ControlToValidate="txtnewpsw2" ErrorMessage="新密码不能为空">*</asp:RequiredFieldValidator> <asp:CompareValidator id="CVpsw" runat="server" ControlToValidate="txtnewpsw2" ErrorMessage="两次密码输入不一致" SetFocusOnError="True" ControlToCompare="txtnewpsw"></asp:CompareValidator></TD></TR><TR><TD style="WIDTH: 378px; HEIGHT: 47px; TEXT-ALIGN: center" align=left colSpan=3>&nbsp;<asp:Button id="btnmd" onclick="btnmd_Click" runat="server" Width="135px" Text="修改密码" Height="47px"></asp:Button></TD></TR></TABLE>
</contenttemplate>
    </asp:UpdatePanel>
</asp:Content>

