//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZY.COM.WS.DataSets.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.89/MsgCenter.asmx")]
        public string HZY_COM_WS_AMSendWS_MsgCenter {
            get {
                return ((string)(this["HZY_COM_WS_AMSendWS_MsgCenter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.202;Initial Catalog=DRPESB_PROD;Persist Security Info=True" +
            ";User ID=sa;Password=ELEGANT.admin")]
        public string DRPESB_PRODConnectionString {
            get {
                return ((string)(this["DRPESB_PRODConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.105;Initial Catalog=StroeBusinissSystem;Persist Security I" +
            "nfo=True;User ID=juge;Password=5516081")]
        public string StroeBusinissSystemConnectionString {
            get {
                return ((string)(this["StroeBusinissSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.105;Initial Catalog=StroeBusinissSystem;Persist Security I" +
            "nfo=True;User ID=sa;Password=nokia13867386635")]
        public string StroeBusinissSystemConnectionString1 {
            get {
                return ((string)(this["StroeBusinissSystemConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.105;Initial Catalog=WSRR;Persist Security Info=True;User I" +
            "D=sa;Password=nokia13867386635")]
        public string WSRRConnectionString {
            get {
                return ((string)(this["WSRRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.105;Initial Catalog=WSRR_Manage;Persist Security Info=True" +
            ";User ID=sa;Password=nokia13867386635")]
        public string WSRR_ManageConnectionString {
            get {
                return ((string)(this["WSRR_ManageConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.105;Initial Catalog=StoreBusinessSystem;Persist Security I" +
            "nfo=True;User ID=juge;Password=5516081")]
        public string StoreBusinessSystemConnectionString {
            get {
                return ((string)(this["StoreBusinessSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.105;Initial Catalog=MDM;User ID=juge;Password=5516081")]
        public string MDMConnectionString {
            get {
                return ((string)(this["MDMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.105;Initial Catalog=VexSSO;User ID=juge;Password=5516081")]
        public string VexSSOConnectionString {
            get {
                return ((string)(this["VexSSOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.205.174;Initial Catalog=DRP_EC;Persist Security Info=True;User" +
            " ID=sa;Password=sql")]
        public string DRP_ECConnectionString {
            get {
                return ((string)(this["DRP_ECConnectionString"]));
            }
        }
    }
}
